
# Spring Configuration
server: 
  port: 8080


# Logging Configuration
logging:
  level:
    it.eng.dome: ${LOG_LEVEL:DEBUG}

tmforumapi:
  tmf620_catalog_url: http://localhost:8100/tmf-api/productCatalogManagement/v4
  tmf622_ordering_url: http://localhost:8000/tmf-api/productOrderingManagement/v4