
# Spring Configuration
server: 
  port: 8080
  servlet:
    context-path:  ${BILLING_PREFIX:/}

# Logging Configuration
logging:
  level:
    it.eng.dome: ${LOG_LEVEL:DEBUG}
    org.apache.coyote.http11: ERROR
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%-5level] %logger{36} - %msg%n" 
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Spring Boot Actuator
management:
  server:
    port: 9000
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: "*"
      base-path: /
      path-mapping:
        health: health
  endpoint:
    health:
      enabled: true
      show-details: never
  health:
    probes:
      enabled: true	

tmforumapi:
  tmf_endpoint: ${TMF_ENDPOINT:http://tm-forum-api}
  
  tmf_envoy:  ${TMF_ENVOY:true}
  # valid only if envoy false
  tmf_namespace:  ${TMF_NAMESPACE:marketplace}
  tmf_postfix:  ${TMF_POSTFIX:svc.cluster.local}
  tmf_port:  ${TMF_PORT:8080}
   
#  tmf_endpoint: http://localhost:8100
  tmf620_catalog_path: tmf-api/productCatalogManagement/v4
#  tmf622_ordering_path: tmf-api/productOrderingManagement/v4
#  tmf678_billing_path: tmf-api/customerBillManagement/v4
  tmf637_billing_path: tmf-api/productInventory/v4
  tmf635_usage_path: tmf-api/usageManagement/v4
  
# schemaLocation relatedParty entity
schema:
  schemaLocation_relatedParty: https://raw.githubusercontent.com/DOME-Marketplace/dome-odrl-profile/refs/heads/main/schemas/simplified/RelatedPartyRef.schema.json 
