name: Build and Test

on:
  push:
    branches: ["main"]

jobs:
  build:
    name: Build Billing Engine
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven

      - name: Build with Maven
        run: cd billing-engine
        run: ls -la


