name: Build and Test

on:
  push:
    branches: ["main"]

jobs:
  build:
    name: Build Billing Engine
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven

      - name: Build with Maven
        run: |
          cd billing-engine
          ls -al
          mvn -B install --file pom.xml

  test:
    name: Test Billing Engine
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven

      - name: Test with Maven
        run: |
          cd billing-engine
          ls -al
          mvn -B test --file pom.xml

  pmd_job:
    name: Static Code Analyzer
    runs-on: ubuntu-latest  
    needs: [test]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven

      - name: Generate PMD report
        id: generate-pmd-report
        uses: pmd/pmd-github-action@v2
        with:
          rulesets: 'rulesets/java/quickstart.xml'
          sourcePath: 'billing-engine/src/main/java'
          analyzeModifiedFilesOnly: false
      
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: pmd-report.sarif

      - name: Fail build if there are violations
        if: steps.generate-pmd-report.outputs.violations > 0
        run: exit 1